export const countryCurrencyArray = [
  { country: "Albania", currencyCode: "ALL" },
  { country: "Algeria", currencyCode: "DZD" },
  { country: "Angola", currencyCode: "AOA" },
  { country: "Argentina", currencyCode: "ARS" },
  { country: "Armenia", currencyCode: "AMD" },
  { country: "Australia", currencyCode: "AUD" },
  { country: "Austria", currencyCode: "EUR" },
  { country: "Azerbaijan", currencyCode: "AZN" },
  { country: "Bahrain", currencyCode: "BHD" },
  { country: "Barbados", currencyCode: "BBD" },
  { country: "Belarus", currencyCode: "BYN" },
  { country: "Belgium", currencyCode: "EUR" },
  { country: "Bermuda", currencyCode: "BMD" },
  { country: "Bolivia", currencyCode: "BOB" },
  { country: "Bosnia and Herzegovina", currencyCode: "BAM" },
  { country: "Botswana", currencyCode: "BWP" },
  { country: "Brazil", currencyCode: "BRL" },
  { country: "Bulgaria", currencyCode: "BGN" },
  { country: "Cabo Verde", currencyCode: "CVE" },
  { country: "Cambodia", currencyCode: "KHR" },
  { country: "Cameroon, Republic of", currencyCode: "XAF" },
  { country: "Canada", currencyCode: "CAD" },
  { country: "Cayman Islands", currencyCode: "KYD" },
  { country: "Chad", currencyCode: "XAF" },
  { country: "Chile", currencyCode: "CLP" },
  { country: "China", currencyCode: "CNY" },
  { country: "Colombia", currencyCode: "COP" },
  { country: "Congo, Democratic Republic of the", currencyCode: "CDF" },
  { country: "Congo, Republic of", currencyCode: "XAF" },
  { country: "Costa Rica", currencyCode: "CRC" },
  { country: "Croatia", currencyCode: "HRK" },
  { country: "Cyprus", currencyCode: "EUR" },
  { country: "Czech Republic", currencyCode: "CZK" },
  { country: "Denmark", currencyCode: "DKK" },
  { country: "Dominican Republic", currencyCode: "DOP" },
  { country: "Ecuador", currencyCode: "USD" },
  { country: "Egypt", currencyCode: "EGP" },
  { country: "El Salvador", currencyCode: "USD" },
  { country: "Equatorial Guinea", currencyCode: "XAF" },
  { country: "Estonia", currencyCode: "EUR" },
  { country: "Ethiopia", currencyCode: "ETB" },
  { country: "Fiji", currencyCode: "FJD" },
  { country: "Finland", currencyCode: "EUR" },
  { country: "France", currencyCode: "EUR" },
  { country: "Gabon", currencyCode: "XAF" },
  { country: "Georgia", currencyCode: "GEL" },
  { country: "Germany", currencyCode: "EUR" },
  { country: "Ghana", currencyCode: "GHS" },
  { country: "Gibraltar", currencyCode: "GIP" },
  { country: "Greece", currencyCode: "EUR" },
  { country: "Greenland", currencyCode: "DKK" },
  { country: "Guatemala", currencyCode: "GTQ" },
  { country: "Guernsey, Channel Islands", currencyCode: "GBP" },
  { country: "Guyana", currencyCode: "GYD" },
  { country: "Honduras", currencyCode: "HNL" },
  { country: "Hong Kong", currencyCode: "HKD" },
  { country: "Hungary", currencyCode: "HUF" },
  { country: "Iceland", currencyCode: "ISK" },
  { country: "India", currencyCode: "INR" },
  { country: "Indonesia", currencyCode: "IDR" },
  { country: "Iraq", currencyCode: "IQD" },
  { country: "Ireland", currencyCode: "EUR" },
  { country: "Isle of Man", currencyCode: "IMP" },
  { country: "Israel", currencyCode: "ILS" },
  { country: "Italy", currencyCode: "EUR" },
  { country: "Ivory Coast (Cote d'Ivoire)", currencyCode: "XOF" },
  { country: "Jamaica", currencyCode: "JMD" },
  { country: "Japan", currencyCode: "JPY" },
  { country: "Jersey, Channel Islands", currencyCode: "GBP" },
  { country: "Jordan", currencyCode: "JOD" },
  { country: "Kazakhstan", currencyCode: "KZT" },
  { country: "Kenya", currencyCode: "KES" },
  { country: "South Korea", currencyCode: "KRW" },
  { country: "Kosovo", currencyCode: "EUR" },
  { country: "Kuwait", currencyCode: "KWD" },
  { country: "Kyrgyzstan", currencyCode: "KGS" },
  { country: "Lao PDR", currencyCode: "LAK" },
  { country: "Latvia", currencyCode: "EUR" },
  { country: "Lebanon", currencyCode: "LBP" },
  { country: "Libya", currencyCode: "LYD" },
  { country: "Liechtenstein", currencyCode: "CHF" },
  { country: "Lithuania", currencyCode: "EUR" },
  { country: "Luxembourg", currencyCode: "EUR" },
  { country: "Macau SAR", currencyCode: "MOP" },
  { country: "Madagascar", currencyCode: "MGA" },
  { country: "Malawi", currencyCode: "MWK" },
  { country: "Malaysia", currencyCode: "MYR" },
  { country: "Maldives, Republic of", currencyCode: "MVR" },
  { country: "Malta", currencyCode: "EUR" },
  { country: "Mauritania", currencyCode: "MRU" },
  { country: "Mauritius", currencyCode: "MUR" },
  { country: "Mexico", currencyCode: "MXN" },
  { country: "Moldova", currencyCode: "MDL" },
  { country: "Mongolia", currencyCode: "MNT" },
  { country: "Montenegro", currencyCode: "EUR" },
  { country: "Morocco", currencyCode: "MAD" },
  { country: "Mozambique", currencyCode: "MZN" },
  { country: "Myanmar", currencyCode: "MMK" },
  { country: "Namibia, Republic of", currencyCode: "NAD" },
  { country: "Netherlands", currencyCode: "EUR" },
  { country: "New Caledonia", currencyCode: "XPF" },
  { country: "New Zealand", currencyCode: "NZD" },
  { country: "Nicaragua", currencyCode: "NIO" },
  { country: "Nigeria", currencyCode: "NGN" },
  { country: "North Macedonia", currencyCode: "MKD" },
  { country: "Norway", currencyCode: "NOK" },
  { country: "Oman", currencyCode: "OMR" },
  { country: "Pakistan", currencyCode: "PKR" },
  { country: "Palestinian territories", currencyCode: "ILS, USD, JOD" },
  { country: "Panama", currencyCode: "PAB, USD" },
  { country: "Papua New Guinea", currencyCode: "PGK" },
  { country: "Paraguay", currencyCode: "PYG" },
  { country: "Peru", currencyCode: "PEN" },
  { country: "Philippines", currencyCode: "PHP" },
  { country: "Poland", currencyCode: "PLN" },
  { country: "Portugal", currencyCode: "EUR" },
  { country: "Puerto Rico", currencyCode: "USD" },
  { country: "Qatar", currencyCode: "QAR" },
  { country: "Romania", currencyCode: "RON" },
  { country: "Russian Federation", currencyCode: "RUB" },
  { country: "Rwanda", currencyCode: "RWF" },
  { country: "Saint Lucia", currencyCode: "XCD" },
  { country: "Saudi Arabia", currencyCode: "SAR" },
  { country: "Senegal", currencyCode: "XOF" },
  { country: "Serbia", currencyCode: "RSD" },
  { country: "Singapore", currencyCode: "SGD" },
  { country: "Slovak Republic", currencyCode: "EUR" },
  { country: "Slovenia", currencyCode: "EUR" },
  { country: "South Africa", currencyCode: "ZAR" },
  { country: "Spain", currencyCode: "EUR" },
  { country: "Sri Lanka", currencyCode: "LKR" },
  { country: "Swaziland", currencyCode: "SZL" },
  { country: "Sweden", currencyCode: "SEK" },
  { country: "Switzerland", currencyCode: "CHF" },
  { country: "Taiwan", currencyCode: "TWD" },
  { country: "Tajikistan", currencyCode: "TJS" },
  { country: "Tanzania", currencyCode: "TZS" },
  { country: "Thailand", currencyCode: "THB" },
  { country: "Timor-Leste", currencyCode: "USD" },
  { country: "Trinidad And Tobago", currencyCode: "TTD" },
  { country: "Tunisia", currencyCode: "TND" },
  { country: "Turkey", currencyCode: "TRY" },
  { country: "Turkmenistan", currencyCode: "TMT" },
  { country: "Uganda", currencyCode: "UGX" },
  { country: "Ukraine", currencyCode: "UAH" },
  { country: "United Arab Emirates", currencyCode: "AED" },
  { country: "United Kingdom", currencyCode: "GBP" },
  { country: "United States", currencyCode: "USD" },
  { country: "Uruguay", currencyCode: "UYU" },
  { country: "Uzbekistan, Republic of", currencyCode: "UZS" },
  { country: "Venezuela", currencyCode: "VEF" },
  { country: "Vietnam", currencyCode: "VND" },
  { country: "Zambia", currencyCode: "ZMW" },
  { country: "Zimbabwe", currencyCode: "ZWD" },
  { country: "Europe", currencyCode: "EUR" },
];
